# Generated by Django 3.2.3 on 2021-05-23 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoPlace',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=300)),
                ('category_group_code', models.CharField(max_length=100)),
                ('category_group_name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('road_address', models.CharField(max_length=300)),
                ('mapx', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mapy', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'kakao_places',
            },
        ),
        migrations.CreateModel(
            name='TourPlace',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300, null=True)),
                ('areacode', models.PositiveSmallIntegerField()),
                ('cat1', models.CharField(max_length=50)),
                ('cat2', models.CharField(max_length=50)),
                ('cat3', models.CharField(max_length=50)),
                ('content_type_id', models.PositiveSmallIntegerField()),
                ('createdtime', models.CharField(max_length=100)),
                ('image1', models.TextField(blank=True)),
                ('image2', models.TextField(blank=True)),
                ('mapx', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mapy', models.DecimalField(decimal_places=6, max_digits=9)),
                ('modifiedtime', models.CharField(max_length=100)),
                ('readcount', models.IntegerField(null=True)),
                ('sigungucode', models.PositiveSmallIntegerField()),
                ('tel', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tour_places',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(max_length=50)),
                ('grade', models.PositiveSmallIntegerField()),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place_kakao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.kakaoplace')),
                ('place_tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.tourplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
