# Generated by Django 3.2.3 on 2021-05-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakaoplace',
            name='place_url',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
