# Generated by Django 3.2.3 on 2021-05-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_kakaoplace_place_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
